# Generated by Django 2.1.3 on 2018-12-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
                ('nombreCordinadores', models.CharField(max_length=45)),
                ('nombresAgentesPastorales', models.CharField(max_length=45)),
                ('nombresMisnistroComunion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('hora', models.CharField(max_length=45)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
    ]
