# Generated by Django 2.1.3 on 2018-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
