# Generated by Django 2.1.3 on 2018-12-03 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentesPatorales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('edad', models.CharField(max_length=45)),
                ('comu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacramento', models.CharField(max_length=45)),
                ('nombreP', models.CharField(max_length=45)),
                ('apellidoP', models.CharField(max_length=45)),
                ('nombreH', models.CharField(max_length=45)),
                ('apellidoH', models.CharField(max_length=45)),
            ],
        ),
    ]
