# Generated by Django 2.1.3 on 2018-12-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentespatorales_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('comuLogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
        migrations.AddField(
            model_name='agentespatorales',
            name='tipoPersona',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
